on: [workflow_dispatch, push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: npm i node-fetch showdown
      - uses: actions/github-script@v4
        id: step
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fetch = require("node-fetch");
            const showdown = require("showdown");
            let r = await fetch("https://api.github.com/users/explosion-scratch/events").then((res) => res.json());
            r = r
              .map((i) => {
                if (i.type === "PushEvent") {
                  return `- [\`${i.payload.commits[0].sha}\`](https://github.com/${i.repo.name}/commit/${i.payload.commits[0].sha})– ${i.payload.commits[0].message} ([${i.repo.name}](https://github.com/${i.repo.name}))`;
                }
                if (i.type === "IssueCommentEvent" && i.payload.action === "created") {
                  return `- Commented in [${i.repo.name}](${
                    i.payload.comment.html_url
                  })<blockquote>${clip(i.payload.comment.body)}</blockquote>`;
                }
                if (i.type === "PullRequestEvent") {
                  let act;
                  if (i.payload.pull_request.merged_by) {
                    act =
                      i.payload.pull_request.merged_by.login === "Explosion-Scratch" &&
                      i.payload.pull_request.merged_at.slice(0, 16) ===
                        i.created_at.slice(0, 16)
                        ? "Merged"
                        : i.payload.action;
                  } else {
                    act = i.payload.action;
                  }
                  return `- ${act} a [pull request](${i.payload.pull_request.html_url}) in [${i.repo.name}](https://github.com/${i.repo.name})`;
                }
              })
              .join("\n");
            var converter = new showdown.Converter();
            return converter.makeHtml(r);
            function clip(str, length = 150){
              let e = str.slice(0, length);
              e += e.length == length ? "..." : "";
              return e.replace(/<(.|\n)*?>/g, "").replace(/\W+/g, " ");
            }
          result-encoding: string
      - run: rm -f test.md
      - name: Get result
        run: echo "${{steps.step.outputs.result}}" > "test.md"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "YEET DID IT WORK?!?!!"
